; Generated by L1S compiler
section .text
global _start

add:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    mov [rbp-24], rdi
    mov [rbp-32], rsi
.entry_0:
    mov rax, [rbp-24]
    mov [rbp-8], rax
    mov rax, [rbp-32]
    mov [rbp-16], rax
    mov rax, [rbp-8]
    mov [rbp-24], rax
    mov rax, [rbp-16]
    mov [rbp-32], rax
    mov rax, [rbp-24]
    add rax, [rbp-32]
    mov rsp, rbp
    pop rbp
    ret

_start:
    call main_func
    mov rdi, rax
    mov rax, 60
    syscall

main_func:
    push rbp
    mov rbp, rsp
    sub rsp, 16
.entry_0:
    mov rax, 10
    mov [rbp-8], rax
    mov rax, 20
    mov [rbp-16], rax
    mov rdi, [rbp-8]
    mov rsi, [rbp-16]
    call add
    mov rsp, rbp
    pop rbp
    ret
main_func_end:

