use crate::ir::*;
use crate::regalloc::*;
use std::collections::HashMap;

pub struct Codegen {
    output: String,
    label_counter: usize,
    current_var_slots: usize,
}

impl Codegen {
    pub fn new() -> Self {
        Codegen {
            output: String::new(),
            label_counter: 0,
            current_var_slots: 0,
        }
    }

    pub fn generate(&mut self, module: &IrModule, allocs: &HashMap<String, Allocation>) -> String {
        self.output.clear();
        self.output.push_str(".intel_syntax noprefix\n");
        self.output.push_str("# Generated by L1S compiler\n");
        self.output.push_str(".text\n");
        self.output.push_str(".globl main\n\n");

        for func in &module.funcs {
            self.emit_function(func, &allocs[&func.name]);
        }

        self.output.clone()
    }

    fn emit_function(&mut self, func: &IrFunction, alloc: &Allocation) {
        self.current_var_slots = func.num_var_slots;
        let var_stack_size = func.num_var_slots * 8;
        let spill_stack_size = alloc.stack_size;
        let total_stack = var_stack_size + spill_stack_size;
        let aligned_size = ((total_stack + 15) & !15).max(8);

        if func.name == "main" {
            self.output.push_str("main:\n");
            self.output.push_str("    call main_func\n");
            self.output.push_str("    ret\n\n");

            self.output.push_str("main_func:\n");
        } else {
            self.output.push_str(&format!("{}:\n", func.name));
        }

        self.output.push_str("    push rbp\n");
        self.output.push_str("    mov rbp, rsp\n");
        if aligned_size > 0 {
            self.output.push_str(&format!("    sub rsp, {}\n", aligned_size));
        }

        // Map params to their VRegs/allocations
        for param in &func.params {
            let loc = self.vreg_loc(param.vreg, alloc);
            // Params come in rdi, rsi, rdx, rcx, r8, r9
            if let Some(param_reg) = self.get_param_reg(param.vreg, &func.params) {
                if loc.starts_with('[') {
                    self.emit(&format!("    mov {}, {}", loc, param_reg));
                } else if loc != param_reg {
                    self.emit(&format!("    mov {}, {}", loc, param_reg));
                }
            }
        }

        // Collect phi resolutions
        let phi_resolves = self.collect_phi_resolves(func, alloc);

        for block in &func.blocks {
            self.output.push_str(&format!("{}_{}:\n", func.name, block.label));

            // First, handle any phi resolutions for this block
            // (moves that should be placed at the end of predecessor blocks)
            // These are emitted as part of the predecessor, not here

            for instr in &block.instrs {
                if matches!(instr, IrInstr::Phi(_, _)) {
                    continue;
                }
                self.emit_instr(instr, alloc);
            }

            match &block.terminator {
                IrTerminator::Ret(Some(vreg)) => {
                    let loc = self.vreg_loc(*vreg, alloc);
                    if loc == "rax" {
                        // already in rax
                    } else {
                        self.emit(&format!("    mov rax, {}", loc));
                    }
                    if func.name == "main" {
                        self.emit("    mov rsp, rbp");
                        self.emit("    pop rbp");
                        self.emit("    ret");
                    } else {
                        self.emit("    mov rsp, rbp");
                        self.emit("    pop rbp");
                        self.emit("    ret");
                    }
                }
                IrTerminator::Ret(None) => {
                    self.emit("    mov rsp, rbp");
                    self.emit("    pop rbp");
                    self.emit("    ret");
                }
                IrTerminator::Br(target) => {
                    // Insert phi resolution moves for the target block
                    if let Some(moves) = phi_resolves.get(&(block.label.clone(), target.clone())) {
                        for (src, dst) in moves {
                            let src_loc = self.vreg_loc(*src, alloc);
                            let dst_loc = self.vreg_loc(*dst, alloc);
                            if src_loc != dst_loc {
                                self.emit(&format!("    mov {}, {}", dst_loc, src_loc));
                            }
                        }
                    }
                    self.emit(&format!("    jmp {}_{}", func.name, target));
                }
                IrTerminator::BrCond(vreg, t, f) => {
                    let loc = self.vreg_loc(*vreg, alloc);
                    if loc.starts_with('[') {
                        self.emit(&format!("    cmp qword ptr {}, 0", loc));
                    } else {
                        self.emit(&format!("    cmp {}, 0", loc));
                    }
                    // Insert phi resolution moves for the "true" branch
                    if let Some(moves) = phi_resolves.get(&(block.label.clone(), t.clone())) {
                        for (src, dst) in moves {
                            let src_loc = self.vreg_loc(*src, alloc);
                            let dst_loc = self.vreg_loc(*dst, alloc);
                            if src_loc != dst_loc {
                                self.emit(&format!("    mov {}, {}", dst_loc, src_loc));
                            }
                        }
                    }
                    self.emit(&format!("    jne {}_{}", func.name, t));
                    // Insert phi resolution moves for the "false" branch
                    if let Some(moves) = phi_resolves.get(&(block.label.clone(), f.clone())) {
                        for (src, dst) in moves {
                            let src_loc = self.vreg_loc(*src, alloc);
                            let dst_loc = self.vreg_loc(*dst, alloc);
                            if src_loc != dst_loc {
                                self.emit(&format!("    mov {}, {}", dst_loc, src_loc));
                            }
                        }
                    }
                    self.emit(&format!("    jmp {}_{}", func.name, f));
                }
                IrTerminator::Unreachable => {
                    self.emit("    ud2");
                }
            }
        }

        if func.name == "main" {
            self.output.push_str("main_func_end:\n");
        }
        self.output.push('\n');
    }

    fn collect_phi_resolves(
        &self,
        func: &IrFunction,
        alloc: &Allocation,
    ) -> HashMap<(String, String), Vec<(VReg, VReg)>> {
        let mut resolves: HashMap<(String, String), Vec<(VReg, VReg)>> = HashMap::new();

        for block in &func.blocks {
            for instr in &block.instrs {
                if let IrInstr::Phi(dest, ops) = instr {
                    for (src, pred_label) in ops {
                        resolves
                            .entry((pred_label.clone(), block.label.clone()))
                            .or_default()
                            .push((*src, *dest));
                    }
                }
            }
        }

        resolves
    }

    fn emit_instr(&mut self, instr: &IrInstr, alloc: &Allocation) {
        match instr {
            IrInstr::Const(vreg, n, _) => {
                let loc = self.vreg_loc(*vreg, alloc);
                if loc.starts_with('[') {
                    self.emit(&format!("    mov rax, {}", n));
                    self.emit(&format!("    mov {}, rax", loc));
                } else {
                    self.emit(&format!("    mov {}, {}", loc, n));
                }
            }
            IrInstr::Add(vreg, a, b) => {
                self.binop("add", "add", *vreg, *a, *b, alloc);
            }
            IrInstr::Sub(vreg, a, b) => {
                self.binop("sub", "sub", *vreg, *a, *b, alloc);
            }
            IrInstr::Mul(vreg, a, b) => {
                self.binop("imul", "imul", *vreg, *a, *b, alloc);
            }
            IrInstr::Div(vreg, a, b) => {
                self.emit_div(*vreg, *a, *b, alloc);
            }
            IrInstr::Eq(vreg, a, b) => {
                self.setcc("sete", *vreg, *a, *b, alloc);
            }
            IrInstr::Neq(vreg, a, b) => {
                self.setcc("setne", *vreg, *a, *b, alloc);
            }
            IrInstr::Lt(vreg, a, b) => {
                self.setcc("setl", *vreg, *a, *b, alloc);
            }
            IrInstr::Gt(vreg, a, b) => {
                self.setcc("setg", *vreg, *a, *b, alloc);
            }
            IrInstr::Le(vreg, a, b) => {
                self.setcc("setle", *vreg, *a, *b, alloc);
            }
            IrInstr::Ge(vreg, a, b) => {
                self.setcc("setge", *vreg, *a, *b, alloc);
            }
            IrInstr::Not(vreg, s) => {
                let dst = self.vreg_loc(*vreg, alloc);
                let src = self.vreg_loc(*s, alloc);
                if dst.starts_with('[') {
                    self.emit(&format!("    mov rax, {}", src));
                    self.emit("    xor rax, 1");
                    self.emit(&format!("    mov {}, rax", dst));
                } else {
                    if dst != src {
                        self.emit(&format!("    mov {}, {}", dst, src));
                    }
                    self.emit(&format!("    xor {}, 1", dst));
                }
            }
            IrInstr::Neg(vreg, s) => {
                let dst = self.vreg_loc(*vreg, alloc);
                let src = self.vreg_loc(*s, alloc);
                if dst.starts_with('[') {
                    self.emit(&format!("    mov rax, {}", src));
                    self.emit("    neg rax");
                    self.emit(&format!("    mov {}, rax", dst));
                } else {
                    if dst != src {
                        self.emit(&format!("    mov {}, {}", dst, src));
                    }
                    self.emit(&format!("    neg {}", dst));
                }
            }
            IrInstr::And(vreg, a, b) => {
                self.binop("and", "and", *vreg, *a, *b, alloc);
            }
            IrInstr::Or(vreg, a, b) => {
                self.binop("or", "or", *vreg, *a, *b, alloc);
            }
            IrInstr::Load(vreg, addr, _) => {
                let dst = self.vreg_loc(*vreg, alloc);
                let src = self.vreg_loc(*addr, alloc);
                if dst.starts_with('[') {
                    self.emit(&format!("    mov rax, [{}]", src));
                    self.emit(&format!("    mov {}, rax", dst));
                } else {
                    self.emit(&format!("    mov {}, [{}]", dst, src));
                }
            }
            IrInstr::Store(val, addr, _) => {
                let vloc = self.vreg_loc(*val, alloc);
                let aloc = self.vreg_loc(*addr, alloc);
                self.emit(&format!("    mov rax, {}", vloc));
                self.emit(&format!("    mov [{}], rax", aloc));
            }
            IrInstr::Alloc(_, _) => {
                // Alloc is no longer emitted; handled by LoadStack/StoreStack
            }
            IrInstr::LoadStack(vreg, slot, _) => {
                let dst = self.vreg_loc(*vreg, alloc);
                let offset = (slot + 1) * 8;
                if dst.starts_with('[') {
                    self.emit(&format!("    mov rax, [rbp-{}]", offset));
                    self.emit(&format!("    mov {}, rax", dst));
                } else {
                    self.emit(&format!("    mov {}, [rbp-{}]", dst, offset));
                }
            }
            IrInstr::StoreStack(val, slot, _) => {
                let vloc = self.vreg_loc(*val, alloc);
                let offset = (slot + 1) * 8;
                self.emit(&format!("    mov rax, {}", vloc));
                self.emit(&format!("    mov [rbp-{}], rax", offset));
            }
            IrInstr::Call(vreg, name, args, _) => {
                // Save caller-saved registers
                for (i, arg) in args.iter().enumerate() {
                    if i < 6 {
                        let arg_reg = self.phys_name(ARG_REGS[i]);
                        let loc = self.vreg_loc(*arg, alloc);
                        self.emit(&format!("    mov {}, {}", arg_reg, loc));
                    } else {
                        // Pass on stack (unlikely for simple language)
                        let loc = self.vreg_loc(*arg, alloc);
                        self.emit(&format!("    push {}", loc));
                    }
                }

                self.emit(&format!("    call {}", if *name == "main" { "main_func" } else { name }));

                let dst = self.vreg_loc(*vreg, alloc);
                if dst.starts_with('[') {
                    self.emit(&format!("    mov {}, rax", dst));
                } else if dst != "rax" {
                    self.emit(&format!("    mov {}, rax", dst));
                }
            }
            IrInstr::Copy(vreg, s) => {
                let dst = self.vreg_loc(*vreg, alloc);
                let src = self.vreg_loc(*s, alloc);
                if dst != src {
                    if dst.starts_with('[') && src.starts_with('[') {
                        self.emit(&format!("    mov rax, {}", src));
                        self.emit(&format!("    mov {}, rax", dst));
                    } else {
                        self.emit(&format!("    mov {}, {}", dst, src));
                    }
                }
            }
            IrInstr::Phi(_, _) => {
                // Phis are resolved by inserting moves at predecessor block ends
            }
        }
    }

    fn binop(
        &mut self,
        _instr: &str,
        asm_op: &str,
        dest: VReg,
        a: VReg,
        b: VReg,
        alloc: &Allocation,
    ) {
        let dst = self.vreg_loc(dest, alloc);
        let aloc = self.vreg_loc(a, alloc);
        let bloc = self.vreg_loc(b, alloc);

        if dst.starts_with('[') && (aloc.starts_with('[') || bloc.starts_with('[')) {
            self.emit(&format!("    mov rax, {}", aloc));
            self.emit(&format!("    {} rax, {}", asm_op, bloc));
            self.emit(&format!("    mov {}, rax", dst));
        } else if dst.starts_with('[') {
            self.emit(&format!("    mov rax, {}", aloc));
            self.emit(&format!("    {} rax, {}", asm_op, bloc));
            self.emit(&format!("    mov {}, rax", dst));
        } else {
            if dst != aloc {
                self.emit(&format!("    mov {}, {}", dst, aloc));
            }
            self.emit(&format!("    {} {}, {}", asm_op, dst, bloc));
        }
    }

    fn setcc(&mut self, cc: &str, dest: VReg, a: VReg, b: VReg, alloc: &Allocation) {
        let dst = self.vreg_loc(dest, alloc);
        let aloc = self.vreg_loc(a, alloc);
        let bloc = self.vreg_loc(b, alloc);

        if dst.starts_with('[') {
            self.emit(&format!("    mov rax, {}", aloc));
            self.emit(&format!("    cmp rax, {}", bloc));
            self.emit(&format!("    {} al", cc));
            self.emit("    movzx rax, al");
            self.emit(&format!("    mov {}, rax", dst));
        } else {
            self.emit(&format!("    mov {}, {}", dst, aloc));
            self.emit(&format!("    cmp {}, {}", dst, bloc));
            self.emit(&format!("    {} al", cc));
            self.emit(&format!("    movzx {}, al", dst));
        }
    }

    fn emit_div(&mut self, dest: VReg, a: VReg, b: VReg, alloc: &Allocation) {
        let dst = self.vreg_loc(dest, alloc);
        let aloc = self.vreg_loc(a, alloc);
        let bloc = self.vreg_loc(b, alloc);
        let scratch = self.get_scratch();

        // Get divisor into a non-rax/rdx register
        self.emit(&format!("    mov {}, {}", scratch, bloc));
        // Get dividend into rax
        self.emit(&format!("    mov rax, {}", aloc));
        self.emit("    cqo");
        self.emit(&format!("    idiv {}", scratch));

        if dst.starts_with('[') {
            self.emit(&format!("    mov {}, rax", dst));
        } else if dst != "rax" {
            self.emit(&format!("    mov {}, rax", dst));
        }
    }

    fn get_scratch(&self) -> String {
        "rcx".to_string()
    }

    fn vreg_loc(&self, vreg: VReg, alloc: &Allocation) -> String {
        if let Some(reg) = alloc.reg_map.get(&vreg) {
            self.phys_name(*reg)
        } else if let Some(slot) = alloc.spill_slots.get(&vreg) {
            format!("[rbp-{}]", self.current_var_slots * 8 + (slot + 1) * 8)
        } else {
            "0".to_string()
        }
    }

    fn phys_name(&self, reg: PhysReg) -> String {
        match reg {
            PhysReg::Rax => "rax".to_string(),
            PhysReg::Rcx => "rcx".to_string(),
            PhysReg::Rdx => "rdx".to_string(),
            PhysReg::Rbx => "rbx".to_string(),
            PhysReg::Rsi => "rsi".to_string(),
            PhysReg::Rdi => "rdi".to_string(),
            PhysReg::R8 => "r8".to_string(),
            PhysReg::R9 => "r9".to_string(),
            PhysReg::R10 => "r10".to_string(),
            PhysReg::R11 => "r11".to_string(),
            PhysReg::R12 => "r12".to_string(),
            PhysReg::R13 => "r13".to_string(),
            PhysReg::R14 => "r14".to_string(),
            PhysReg::R15 => "r15".to_string(),
        }
    }

    fn get_param_reg(&self, vreg: VReg, params: &[IrParam]) -> Option<String> {
        for (i, p) in params.iter().enumerate() {
            if p.vreg == vreg && i < 6 {
                return Some(self.phys_name(ARG_REGS[i]));
            }
        }
        None
    }

    fn emit(&mut self, line: &str) {
        self.output.push_str(line);
        self.output.push('\n');
    }
}
