use std::fmt;

#[derive(Clone, Debug, PartialEq)]
pub enum Token {
    Func,
    Let,
    Return,
    If,
    Else,
    While,
    True,
    False,
    I32,
    I64,
    U32,
    U64,
    I8,
    U8,
    Bool,
    Void,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Comma,
    Semicolon,
    Colon,
    Arrow,
    Plus,
    Minus,
    Star,
    Slash,
    Assign,
    Eq,
    Neq,
    Lt,
    Gt,
    Le,
    Ge,
    AndAnd,
    OrOr,
    Not,
    IntLit(i64),
    Ident(String),
    EOF,
    Error(String),
}

pub fn keyword_token(s: &str) -> Option<Token> {
    match s {
        "func" => Some(Token::Func),
        "let" => Some(Token::Let),
        "return" => Some(Token::Return),
        "if" => Some(Token::If),
        "else" => Some(Token::Else),
        "while" => Some(Token::While),
        "true" => Some(Token::True),
        "false" => Some(Token::False),
        "i32" => Some(Token::I32),
        "i64" => Some(Token::I64),
        "u32" => Some(Token::U32),
        "u64" => Some(Token::U64),
        "i8" => Some(Token::I8),
        "u8" => Some(Token::U8),
        "bool" => Some(Token::Bool),
        "void" => Some(Token::Void),
        _ => None,
    }
}

impl fmt::Display for Token {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Token::Func => write!(f, "func"),
            Token::Let => write!(f, "let"),
            Token::Return => write!(f, "return"),
            Token::If => write!(f, "if"),
            Token::Else => write!(f, "else"),
            Token::While => write!(f, "while"),
            Token::True => write!(f, "true"),
            Token::False => write!(f, "false"),
            Token::I32 => write!(f, "i32"),
            Token::I64 => write!(f, "i64"),
            Token::U32 => write!(f, "u32"),
            Token::U64 => write!(f, "u64"),
            Token::I8 => write!(f, "i8"),
            Token::U8 => write!(f, "u8"),
            Token::Bool => write!(f, "bool"),
            Token::Void => write!(f, "void"),
            Token::LParen => write!(f, "("),
            Token::RParen => write!(f, ")"),
            Token::LBrace => write!(f, "{{"),
            Token::RBrace => write!(f, "}}"),
            Token::LBracket => write!(f, "["),
            Token::RBracket => write!(f, "]"),
            Token::Comma => write!(f, ","),
            Token::Semicolon => write!(f, ";"),
            Token::Colon => write!(f, ":"),
            Token::Arrow => write!(f, "->"),
            Token::Plus => write!(f, "+"),
            Token::Minus => write!(f, "-"),
            Token::Star => write!(f, "*"),
            Token::Slash => write!(f, "/"),
            Token::Assign => write!(f, "="),
            Token::Eq => write!(f, "=="),
            Token::Neq => write!(f, "!="),
            Token::Lt => write!(f, "<"),
            Token::Gt => write!(f, ">"),
            Token::Le => write!(f, "<="),
            Token::Ge => write!(f, ">="),
            Token::AndAnd => write!(f, "&&"),
            Token::OrOr => write!(f, "||"),
            Token::Not => write!(f, "!"),
            Token::IntLit(n) => write!(f, "{}", n),
            Token::Ident(s) => write!(f, "{}", s),
            Token::EOF => write!(f, "EOF"),
            Token::Error(e) => write!(f, "error({})", e),
        }
    }
}
